name: Unit Tests

on: [push, workflow_dispatch]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup auth token
              run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

            - name: Install dependencies
              run: npm install
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Build
              run: npm run build

            - name: Test
              run: npm run test:coverage
